'use client';

import { useState, useEffect } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  TextField,
  CircularProgress,
  Checkbox,
  Box,
  Typography,
  Chip,
} from '@mui/material';
import { IconSearch, IconX } from '@tabler/icons-react';
import { safeFormatCurrency } from '@/utils/currency';
import TypeBadge from '@/app/admin/food-items/components/TypeBadge';

interface FoodItem {
  _id: string;
  name: string;
  description?: string;
  veg: boolean;
  price?: number;
  itemType?: 'simple' | 'portions' | 'combo';
  portions?: string[];
  portionPrices?: number[];
}

interface AddItemDialogProps {
  open: boolean;
  categoryId: string;
  existingItemIds: string[];
  token: string;
  onClose: () => void;
  onItemsAdded: () => void;
}

export default function AddItemDialog({
  open,
  categoryId,
  existingItemIds,
  token,
  onClose,
  onItemsAdded,
}: AddItemDialogProps) {
  const [allItems, setAllItems] = useState<FoodItem[]>([]);
  const [filteredItems, setFilteredItems] = useState<FoodItem[]>([]);
  const [selectedItemIds, setSelectedItemIds] = useState<string[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  // Fetch all available food items when dialog opens
  useEffect(() => {
    if (open) {
      fetchItems();
    }
  }, [open, token]);

  // Filter items based on search query and exclude existing items
  useEffect(() => {
    let filtered = allItems;

    // Exclude items already in this category
    filtered = filtered.filter((item) => !existingItemIds.includes(item._id));

    // Apply search filter
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase().trim();
      filtered = filtered.filter((item) =>
        item.name.toLowerCase().includes(query) ||
        (item.description && item.description.toLowerCase().includes(query))
      );
    }

    setFilteredItems(filtered);
  }, [allItems, searchQuery, existingItemIds]);

  const fetchItems = async () => {
    setLoading(true);
    setError('');

    try {
      const response = await fetch('/api/admin/food-items?excludeDrafts=true&limit=10000', {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (!response.ok) {
        throw new Error('Failed to fetch food items');
      }

      const data = await response.json();
      const items = data.data?.items || [];
      setAllItems(items);
      setSelectedItemIds(existingItemIds);
      setSearchQuery('');
    } catch (err) {
      console.error('Error fetching items:', err);
      setError(err instanceof Error ? err.message : 'Failed to load items');
    } finally {
      setLoading(false);
    }
  };

  const handleToggleItem = (itemId: string) => {
    setSelectedItemIds((prev) =>
      prev.includes(itemId)
        ? prev.filter((id) => id !== itemId)
        : [...prev, itemId]
    );
  };

  const handleSelectAll = () => {
    if (selectedItemIds.length === filteredItems.length) {
      setSelectedItemIds([]);
    } else {
      setSelectedItemIds(filteredItems.map((item) => item._id));
    }
  };

  const handleAddItems = async () => {
    if (selectedItemIds.length === 0) {
      setError('Please select at least one item');
      return;
    }

    setSaving(true);
    setError('');

    try {
      // Create category mappings for each selected item
      const createPromises = selectedItemIds.map(async (itemId) => {
        const response = await fetch('/api/admin/category-food-mapping', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({
            foodItemId: itemId,
            categoryId: categoryId,
            // sequence will be auto-generated by the API
          }),
        });

        if (!response.ok) {
          const errorData = await response.json();

          // Handle duplicate mapping (409) gracefully
          if (response.status === 409) {
            console.warn(`Mapping already exists for item ${itemId}`);
            return null; // Skip duplicates
          }

          throw new Error(errorData.error || `Failed to add item ${itemId}`);
        }

        return response.json();
      });

      await Promise.all(createPromises);

      // Close dialog and trigger refresh
      onItemsAdded();
      handleClose();
    } catch (err) {
      console.error('Error adding items:', err);
      setError(err instanceof Error ? err.message : 'Failed to add items');
    } finally {
      setSaving(false);
    }
  };

  const handleClose = () => {
    if (!saving) {
      setSelectedItemIds([]);
      setSearchQuery('');
      setError('');
      onClose();
    }
  };

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      maxWidth="md"
      fullWidth
      PaperProps={{
        sx: {
          borderRadius: 3,
          maxHeight: '80vh',
        },
      }}
    >
      <DialogTitle sx={{ fontWeight: 600, fontSize: '1.25rem', pb: 1 }}>
        Add Items to Category
        {selectedItemIds.length > 0 && (
          <Chip
            label={`${selectedItemIds.length} selected`}
            size="small"
            sx={{
              ml: 2,
              backgroundColor: '#4F8CFF',
              color: 'white',
              fontWeight: 500,
            }}
          />
        )}
      </DialogTitle>

      <DialogContent sx={{ overflowY: 'auto' }}>
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: 1 }}>
          {error && (
            <Typography variant="body2" sx={{ color: '#F44336', mb: 1 }}>
              {error}
            </Typography>
          )}

          {/* Search Field */}
          <TextField
            placeholder="Search items by name or description..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            disabled={loading || saving}
            fullWidth
            autoFocus
            InputProps={{
              startAdornment: <IconSearch size={20} style={{ marginRight: 8, color: '#666' }} />,
              endAdornment: searchQuery && (
                <Button
                  size="small"
                  onClick={() => setSearchQuery('')}
                  disabled={saving}
                  sx={{ minWidth: 'auto', p: 0.5 }}
                >
                  <IconX size={16} />
                </Button>
              ),
            }}
            sx={{
              '& .MuiOutlinedInput-root': {
                backgroundColor: '#F6FAFF',
                '&:hover fieldset': {
                  borderColor: '#4F8CFF',
                },
                '&.Mui-focused fieldset': {
                  borderColor: '#4F8CFF',
                },
              },
            }}
          />

          {/* Select All Checkbox */}
          {filteredItems.length > 0 && (
            <Box
              sx={{
                display: 'flex',
                alignItems: 'center',
                p: 1.5,
                backgroundColor: '#F6FAFF',
                borderRadius: 1,
                border: '1px solid #E0E0E0',
              }}
            >
              <Checkbox
                checked={selectedItemIds.length === filteredItems.length && filteredItems.length > 0}
                indeterminate={
                  selectedItemIds.length > 0 && selectedItemIds.length < filteredItems.length
                }
                onChange={handleSelectAll}
                disabled={saving}
                sx={{
                  '&.Mui-checked': {
                    color: '#4F8CFF',
                  },
                }}
              />
              <Typography variant="body2" sx={{ fontWeight: 500, color: '#333' }}>
                {selectedItemIds.length === filteredItems.length
                  ? 'Deselect All'
                  : 'Select All'}
              </Typography>
              <Typography variant="caption" sx={{ color: '#666', ml: 1 }}>
                ({filteredItems.length} items available)
              </Typography>
            </Box>
          )}

          {/* Loading State */}
          {loading ? (
            <Box sx={{ display: 'flex', justifyContent: 'center', py: 4 }}>
              <CircularProgress sx={{ color: '#4F8CFF' }} />
            </Box>
          ) : filteredItems.length === 0 ? (
            /* Empty State */
            <Box
              sx={{
                textAlign: 'center',
                py: 4,
                backgroundColor: '#FAFAFA',
                borderRadius: 1,
              }}
            >
              <Typography variant="body2" sx={{ color: '#666' }}>
                {searchQuery
                  ? 'No items match your search'
                  : 'All items are already added to this category'}
              </Typography>
            </Box>
          ) : (
            /* Items List */
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
              {filteredItems.map((item) => (
                <Box
                  key={item._id}
                  onClick={() => !saving && handleToggleItem(item._id)}
                  sx={{
                    display: 'flex',
                    alignItems: 'center',
                    p: 2,
                    borderRadius: 1,
                    border: '1px solid #E0E0E0',
                    backgroundColor: selectedItemIds.includes(item._id)
                      ? 'rgba(79, 140, 255, 0.08)'
                      : '#FAFAFA',
                    cursor: saving ? 'not-allowed' : 'pointer',
                    transition: 'all 0.2s',
                    '&:hover': {
                      borderColor: '#4F8CFF',
                      backgroundColor: selectedItemIds.includes(item._id)
                        ? 'rgba(79, 140, 255, 0.12)'
                        : 'rgba(79, 140, 255, 0.04)',
                    },
                  }}
                >
                  <Checkbox
                    checked={selectedItemIds.includes(item._id)}
                    onChange={() => handleToggleItem(item._id)}
                    onClick={(e) => e.stopPropagation()}
                    disabled={saving}
                    sx={{
                      '&.Mui-checked': {
                        color: '#4F8CFF',
                      },
                    }}
                  />

                  <Box
                    sx={{
                      width: 12,
                      height: 12,
                      borderRadius: '50%',
                      backgroundColor: item.veg ? '#4CAF50' : '#F44336',
                      mr: 2,
                      flexShrink: 0,
                    }}
                  />

                  <Box sx={{ mr: 1.5, flexShrink: 0 }}>
                    <TypeBadge type={item.itemType || 'simple'} />
                  </Box>

                  <Box sx={{ flex: 1, minWidth: 0 }}>
                    <Typography
                      variant="body2"
                      sx={{
                        fontWeight: 500,
                        color: '#333',
                      }}
                    >
                      {item.name}
                    </Typography>
                    {item.description && (
                      <Typography
                        variant="caption"
                        sx={{
                          color: '#666',
                          display: 'block',
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                          whiteSpace: 'nowrap',
                        }}
                      >
                        {item.description}
                      </Typography>
                    )}
                  </Box>

                  <Typography
                    variant="body2"
                    sx={{
                      fontWeight: 600,
                      color: '#4F8CFF',
                      ml: 2,
                      flexShrink: 0,
                    }}
                  >
                    {item.itemType === 'portions' &&
                    item.portionPrices &&
                    item.portionPrices.length > 0 ? (
                      <>
                        {safeFormatCurrency(Math.min(...item.portionPrices))} -{' '}
                        {safeFormatCurrency(Math.max(...item.portionPrices))}
                      </>
                    ) : item.price !== undefined && item.price !== null ? (
                      safeFormatCurrency(item.price)
                    ) : (
                      'N/A'
                    )}
                  </Typography>
                </Box>
              ))}
            </Box>
          )}
        </Box>
      </DialogContent>

      <DialogActions sx={{ p: 3, gap: 1 }}>
        <Button
          onClick={handleClose}
          disabled={saving}
          sx={{
            textTransform: 'none',
            color: '#666',
          }}
        >
          Cancel
        </Button>
        <Button
          onClick={handleAddItems}
          disabled={saving || selectedItemIds.length === 0}
          variant="contained"
          startIcon={saving ? <CircularProgress size={16} color="inherit" /> : null}
          sx={{
            textTransform: 'none',
            backgroundColor: '#4F8CFF',
            minWidth: 100,
            '&:hover': {
              backgroundColor: '#3B7AE8',
            },
          }}
        >
          {saving ? 'Adding...' : `Add ${selectedItemIds.length} Item${selectedItemIds.length !== 1 ? 's' : ''}`}
        </Button>
      </DialogActions>
    </Dialog>
  );
}
